export const StatusIcon = {
  true: "/assets/icons/check.svg",
  false: "/assets/icons/cancelled.svg",
};

export const clientDefaultValue = {
  regNumber: "",
  name: "",
  age: "",
  email: "",
  gender: "Male" as "Male" | "Female",
  marital: "Single" as "Single" | "Married" | "Divorced" | "Widowed",
  address: "",
  phoneNumber: "",
  medicalClearance: "true" as "true" | "false",
  // currentHealthIssue: "None",
  nextOfKin: "",
  nextOfKinPhoneNumber: "",
  currentWeight: "",
  currentHeight: "",
  dateOfRegistration: new Date(),
  subscriptionStartingDate: new Date(),
  typeOfSubscription: "",
  paymentConfirmed: "true" as "true" | "false",
};
export const RegisterDefaultValue = {
  regNumber: "",
  name: "",
  subscriptionStartingDate: new Date(),
  typeOfSubscription: "",
  paymentConfirmed: "false" as "true" | "false",
};

export const genderOptions = ["Male", "Female"];
export const maritalStatus = ["Single", "Married", "Divorced", "Widowed"];

export const medicalClearance = [true, false];

export const subscriptionTypes = [
  { name: "Individual-daily", duration: 1 },
  { name: "Individual-weekly", duration: 7 },
  { name: "Individual-biweekly", duration: 14 },
  { name: "Individual-monthly", duration: 30 },
  { name: "Individual-bimonthly", duration: 60 },
  { name: "Individual-quarterly", duration: 90 },
  { name: "Individual-semiannual", duration: 180 },
  { name: "Individual-annual", duration: 365 },
  { name: "Couple-monthly", duration: 30 },
  { name: "Couple-bimonthly", duration: 60 },
  { name: "Couple-quarterly", duration: 90 },
  { name: "Couple-semiannual", duration: 180 },
  { name: "Couple-annual", duration: 365 },
  { name: "Family4-monthly", duration: 30 },
  { name: "Family4-bimonthly", duration: 60 },
  { name: "Family4-quarterly", duration: 90 },
  { name: "Family4-semiannual", duration: 180 },
  { name: "Family4-annual", duration: 365 },
];

export const users = [
  {
    regNumber: "10001",
    name: "John Doe",
    age: "30",
    email: "john.doe@example.com",
    gender: "Male",
    marital: "Single",
    address: "456 Elm St, Springfield",
    phoneNumber: "+1234567890",
    medicalClearance: "true",
    currentHealthIssue: "None",
    nextOfKin: "Jane Doe",
    nextOfKinPhoneNumber: "+1987654320",
    currentWeight: "80",
    currentHeight: "175",
    dateOfRegistration: new Date("2024-01-01"),
    subscriptionStartingDate: new Date("2024-01-15"),
    typeOfSubscription: "Standard",
    paymentConfirmed: "true",
  },
  {
    regNumber: "10002",
    name: "Jane Smith",
    age: "28",
    email: "jane.smith@example.com",
    gender: "Female",
    marital: "Married",
    address: "789 Oak St, Springfield",
    phoneNumber: "+1234567891",
    medicalClearance: "true",
    currentHealthIssue: "Asthma",
    nextOfKin: "John Smith",
    nextOfKinPhoneNumber: "+1987654321",
    currentWeight: "65",
    currentHeight: "165",
    dateOfRegistration: new Date("2024-01-02"),
    subscriptionStartingDate: new Date("2024-01-16"),
    typeOfSubscription: "Premium",
    paymentConfirmed: "true",
  },
  {
    regNumber: "10003",
    name: "Michael Johnson",
    age: "35",
    email: "michael.johnson@example.com",
    gender: "Male",
    marital: "Single",
    address: "101 Pine St, Springfield",
    phoneNumber: "+1234567892",
    medicalClearance: "true",
    currentHealthIssue: "Diabetes",
    nextOfKin: "Sarah Johnson",
    nextOfKinPhoneNumber: "+1987654322",
    currentWeight: "95",
    currentHeight: "185",
    dateOfRegistration: new Date("2024-01-03"),
    subscriptionStartingDate: new Date("2024-01-17"),
    typeOfSubscription: "Standard",

    paymentConfirmed: "true",
  },
  {
    regNumber: "10004",
    name: "Emily Davis",
    age: "40",
    email: "emily.davis@example.com",
    gender: "Female",
    marital: "Divorced",
    address: "102 Maple St, Springfield",
    phoneNumber: "+1234567893",
    medicalClearance: "true",
    currentHealthIssue: "None",
    nextOfKin: "Mark Davis",
    nextOfKinPhoneNumber: "+1987654323",
    currentWeight: "70",
    currentHeight: "170",
    dateOfRegistration: new Date("2024-01-04"),
    subscriptionStartingDate: new Date("2024-01-18"),
    typeOfSubscription: "Basic",

    paymentConfirmed: "true",
  },
  {
    regNumber: "10005",
    name: "David Wilson",
    age: "50",
    email: "david.wilson@example.com",
    gender: "Male",
    marital: "Married",
    address: "103 Cedar St, Springfield",
    phoneNumber: "+1234567894",
    medicalClearance: "true",
    currentHealthIssue: "Hypertension",
    nextOfKin: "Laura Wilson",
    nextOfKinPhoneNumber: "+1987654324",
    currentWeight: "85",
    currentHeight: "180",
    dateOfRegistration: new Date("2024-01-05"),
    subscriptionStartingDate: new Date("2024-01-19"),
    typeOfSubscription: "Standard",

    paymentConfirmed: "true",
  },
  {
    regNumber: "10006",
    name: "Sarah Lee",
    age: "32",
    email: "sarah.lee@example.com",
    gender: "Female",
    marital: "Single",
    address: "104 Birch St, Springfield",
    phoneNumber: "+1234567895",
    medicalClearance: "true",
    currentHealthIssue: "None",
    nextOfKin: "James Lee",
    nextOfKinPhoneNumber: "+1987654325",
    currentWeight: "60",
    currentHeight: "160",
    dateOfRegistration: new Date("2024-01-06"),
    subscriptionStartingDate: new Date("2024-01-20"),
    typeOfSubscription: "Premium",

    paymentConfirmed: "true",
  },
  {
    regNumber: "10007",
    name: "George Miller",
    age: "45",
    email: "george.miller@example.com",
    gender: "Male",
    marital: "Married",
    address: "123 Main St, Springfield",
    phoneNumber: "+1234567897",
    medicalClearance: "true",
    currentHealthIssue: "None",
    nextOfKin: "Jane Miller",
    nextOfKinPhoneNumber: "+1987654321",
    currentWeight: "90",
    currentHeight: "180",
    dateOfRegistration: new Date("2024-01-10"),
    subscriptionStartingDate: new Date("2024-01-30"),
    typeOfSubscription: "Premium",

    paymentConfirmed: "true",
  },
  {
    regNumber: "10008",
    name: "Nancy Brown",
    age: "38",
    email: "nancy.brown@example.com",
    gender: "Female",
    marital: "Married",
    address: "105 Walnut St, Springfield",
    phoneNumber: "+1234567898",
    medicalClearance: "true",
    currentHealthIssue: "Arthritis",
    nextOfKin: "Robert Brown",
    nextOfKinPhoneNumber: "+1987654326",
    currentWeight: "68",
    currentHeight: "168",
    dateOfRegistration: new Date("2024-01-11"),
    subscriptionStartingDate: new Date("2024-01-31"),
    typeOfSubscription: "Standard",
    paymentConfirmed: "true",
  },
  {
    regNumber: "10009",
    name: "William White",
    age: "55",
    email: "william.white@example.com",
    gender: "Male",
    marital: "Married",
    address: "106 Chestnut St, Springfield",
    phoneNumber: "+1234567899",
    medicalClearance: "true",
    currentHealthIssue: "None",
    nextOfKin: "Mary White",
    nextOfKinPhoneNumber: "+1987654327",
    currentWeight: "88",
    currentHeight: "175",
    dateOfRegistration: new Date("2024-01-12"),
    subscriptionStartingDate: new Date("2024-02-01"),
    typeOfSubscription: "Premium",
    paymentConfirmed: "true",
  },
  {
    regNumber: "10010",
    name: "Patricia Green",
    age: "29",
    email: "patricia.green@example.com",
    gender: "Female",
    marital: "Single",
    address: "107 Spruce St, Springfield",
    phoneNumber: "+1234567800",
    medicalClearance: "true",
    currentHealthIssue: "None",
    nextOfKin: "Daniel Green",
    nextOfKinPhoneNumber: "+1987654328",
    currentWeight: "58",
    currentHeight: "162",
    dateOfRegistration: new Date("2024-01-13"),
    subscriptionStartingDate: new Date("2024-02-02"),
    typeOfSubscription: "Basic",
    paymentConfirmed: "true",
  },
];
