export const StatusIcon = {
  true: "/assets/icons/check.svg",
  false: "/assets/icons/cancelled.svg",
};

export const clientDefaultValue = {
  regNumber: "",
  name: "",
  age: "",
  email: "",
  gender: "Male" as "Male" | "Female",
  marital: "Single" as "Single" | "Married" | "Divorced" | "Widowed",
  address: "",
  phoneNumber: "",
  medicalClearance: "false" as "true" | "false",
  currentHealthIssue: "",
  nextOfKin: "",
  nextOfKinPhoneNumber: "",
  currentWeight: "",
  currentHeight: "",
  dateOfRegistration: new Date(),
  subscriptionStartingDate: new Date(),
  typeOfSubscription: "",
  paymentConfirmed: "false" as "true" | "false",
};
export const RegisterDefaultValue = {
  regNumber: "",
  name: "",
  subscriptionStartingDate: new Date(),
  typeOfSubscription: "",
  paymentConfirmed: "false" as "true" | "false",
};

export const genderOptions = ["Male", "Female"];
export const maritalStatus = ["Single", "Married", "Divorced", "Widowed"];

export const medicalClearance = [true, false];

export const subscriptionTypes = [
  {
    name: "individual-daily",
    cost: 3000,
  },
  {
    name: "individual-weekly",
    cost: 10000,
  },
  {
    name: "individual-biweekly",
    cost: 20000,
  },
  {
    name: "individual-monthly",
    cost: 20000,
  },
  {
    name: "individual-bimonthly",
    cost: 35000,
  },
  {
    name: "individual-quarterly",
    cost: 50000,
  },
  {
    name: "individual-semiannual",
    cost: 80000,
  },
  {
    name: "individual-annual",
    cost: 140000,
  },
  {
    name: "couple-monthly",
    cost: 35000,
  },
  {
    name: "couple-bimonthly",
    cost: 60000,
  },
  {
    name: "couple-quarterly",
    cost: 80000,
  },
  {
    name: "couple-semiannual",
    cost: 130000,
  },
  {
    name: "couple-annual",
    cost: 240000,
  },
  {
    name: "family4-monthly",
    cost: 60000,
  },
  {
    name: "family4-bimonthly",
    cost: 100000,
  },
  {
    name: "family4-quarterly",
    cost: 140000,
  },
  {
    name: "family4-semiannual",
    cost: 200000,
  },
  {
    name: "family4-annual",
    cost: 380000,
  },
];

export const data = [
  {
    regNumber: "10001",
    name: "Alice Johnson",
    phoneNumber: "+1234567891",
    typeOfSubscription: "Basic",
    subscriptionActive: true,
    paymentConfirmed: true,
    dateOfRegistration: new Date("2024-02-01"),
    numberOfDaysRemaining: 25,
    subscriptionStartingDate: new Date("2024-03-01"),
  },
  {
    regNumber: "10002",
    name: "Bob Smith",
    phoneNumber: "+1234567892",
    typeOfSubscription: "Premium",
    subscriptionActive: true,
    paymentConfirmed: false,
    dateOfRegistration: new Date("2024-02-10"),
    numberOfDaysRemaining: 40,
    subscriptionStartingDate: new Date("2024-03-05"),
  },
  {
    regNumber: "10003",
    name: "Charlie Brown",
    phoneNumber: "+1234567893",
    typeOfSubscription: "Standard",
    subscriptionActive: false,
    paymentConfirmed: true,
    dateOfRegistration: new Date("2024-01-20"),
    numberOfDaysRemaining: 0,
    subscriptionStartingDate: new Date("2024-02-15"),
  },
  {
    regNumber: "10004",
    name: "Diana Prince",
    phoneNumber: "+1234567894",
    typeOfSubscription: "Premium",
    subscriptionActive: true,
    paymentConfirmed: true,
    dateOfRegistration: new Date("2024-03-01"),
    numberOfDaysRemaining: 60,
    subscriptionStartingDate: new Date("2024-03-15"),
  },
  {
    regNumber: "10005",
    name: "Edward King",
    phoneNumber: "+1234567895",
    typeOfSubscription: "Basic",
    subscriptionActive: false,
    paymentConfirmed: false,
    dateOfRegistration: new Date("2024-01-15"),
    numberOfDaysRemaining: 0,
    subscriptionStartingDate: new Date("2024-01-20"),
  },
  {
    regNumber: "10006",
    name: "Fiona Amith",
    phoneNumber: "+1234567896",
    typeOfSubscription: "Standard",
    subscriptionActive: true,
    paymentConfirmed: true,
    dateOfRegistration: new Date("2024-02-18"),
    numberOfDaysRemaining: 45,
    subscriptionStartingDate: new Date("2024-02-28"),
  },
  {
    regNumber: "10007",
    name: "Goerge Miller",
    phoneNumber: "+1234567897",
    typeOfSubscription: "Premium",
    subscriptionActive: false,
    paymentConfirmed: false,
    dateOfRegistration: new Date("2024-01-10"),
    numberOfDaysRemaining: 0,
    subscriptionStartingDate: new Date("2024-01-30"),
  },
  {
    regNumber: "10008",
    name: "Hannah Clark",
    phoneNumber: "+1234567898",
    typeOfSubscription: "Basic",
    subscriptionActive: true,
    paymentConfirmed: true,
    dateOfRegistration: new Date("2024-02-22"),
    numberOfDaysRemaining: 20,
    subscriptionStartingDate: new Date("2024-03-10"),
  },
  {
    regNumber: "10009",
    name: "Ian Scott",
    phoneNumber: "+1234567899",
    typeOfSubscription: "Standard",
    subscriptionActive: true,
    paymentConfirmed: false,
    dateOfRegistration: new Date("2024-01-25"),
    numberOfDaysRemaining: 15,
    subscriptionStartingDate: new Date("2024-02-05"),
  },
  {
    regNumber: "10010",
    name: "Jane Doe",
    phoneNumber: "+1234567800",
    typeOfSubscription: "Premium",
    subscriptionActive: true,
    paymentConfirmed: true,
    dateOfRegistration: new Date("2024-03-05"),
    numberOfDaysRemaining: 90,
    subscriptionStartingDate: new Date("2024-03-20"),
  },
  {
    regNumber: "10006",
    name: "Alice Johnson",
    phoneNumber: "+1234567896",
    typeOfSubscription: "Premium",
    subscriptionActive: true,
    paymentConfirmed: true,
    dateOfRegistration: new Date("2024-02-10"),
    numberOfDaysRemaining: 30,
    subscriptionStartingDate: new Date("2024-02-15"),
  },
  {
    regNumber: "10007",
    name: "John Doe",
    phoneNumber: "+1234567897",
    typeOfSubscription: "Standard",
    subscriptionActive: false,
    paymentConfirmed: false,
    dateOfRegistration: new Date("2024-03-05"),
    numberOfDaysRemaining: 0,
    subscriptionStartingDate: new Date("2024-03-10"),
  },
  {
    regNumber: "10008",
    name: "Mary Smith",
    phoneNumber: "+1234567898",
    typeOfSubscription: "Basic",
    subscriptionActive: true,
    paymentConfirmed: true,
    dateOfRegistration: new Date("2024-04-01"),
    numberOfDaysRemaining: 15,
    subscriptionStartingDate: new Date("2024-04-05"),
  },
  {
    regNumber: "10009",
    name: "James Williams",
    phoneNumber: "+1234567899",
    typeOfSubscription: "Premium",
    subscriptionActive: true,
    paymentConfirmed: true,
    dateOfRegistration: new Date("2024-05-20"),
    numberOfDaysRemaining: 25,
    subscriptionStartingDate: new Date("2024-05-25"),
  },
  {
    regNumber: "10010",
    name: "Patricia Brown",
    phoneNumber: "+1234567800",
    typeOfSubscription: "Standard",
    subscriptionActive: false,
    paymentConfirmed: false,
    dateOfRegistration: new Date("2024-06-15"),
    numberOfDaysRemaining: 0,
    subscriptionStartingDate: new Date("2024-06-20"),
  },
  {
    regNumber: "10011",
    name: "Robert Jones",
    phoneNumber: "+1234567801",
    typeOfSubscription: "Basic",
    subscriptionActive: true,
    paymentConfirmed: true,
    dateOfRegistration: new Date("2024-07-10"),
    numberOfDaysRemaining: 10,
    subscriptionStartingDate: new Date("2024-07-15"),
  },
  {
    regNumber: "10012",
    name: "Linda Garcia",
    phoneNumber: "+1234567802",
    typeOfSubscription: "Premium",
    subscriptionActive: true,
    paymentConfirmed: true,
    dateOfRegistration: new Date("2024-08-05"),
    numberOfDaysRemaining: 20,
    subscriptionStartingDate: new Date("2024-08-10"),
  },
  {
    regNumber: "10013",
    name: "Michael Martinez",
    phoneNumber: "+1234567803",
    typeOfSubscription: "Standard",
    subscriptionActive: false,
    paymentConfirmed: false,
    dateOfRegistration: new Date("2024-09-01"),
    numberOfDaysRemaining: 0,
    subscriptionStartingDate: new Date("2024-09-05"),
  },
  {
    regNumber: "10014",
    name: "Barbara Rodriguez",
    phoneNumber: "+1234567804",
    typeOfSubscription: "Basic",
    subscriptionActive: true,
    paymentConfirmed: true,
    dateOfRegistration: new Date("2024-10-15"),
    numberOfDaysRemaining: 5,
    subscriptionStartingDate: new Date("2024-10-20"),
  },
  {
    regNumber: "10015",
    name: "William Clark",
    phoneNumber: "+1234567805",
    typeOfSubscription: "Premium",
    subscriptionActive: true,
    paymentConfirmed: true,
    dateOfRegistration: new Date("2024-11-01"),
    numberOfDaysRemaining: 30,
    subscriptionStartingDate: new Date("2024-11-05"),
  },
  {
    regNumber: "10016",
    name: "Elizabeth Lewis",
    phoneNumber: "+1234567806",
    typeOfSubscription: "Standard",
    subscriptionActive: false,
    paymentConfirmed: false,
    dateOfRegistration: new Date("2024-12-15"),
    numberOfDaysRemaining: 0,
    subscriptionStartingDate: new Date("2024-12-20"),
  },
  {
    regNumber: "10017",
    name: "David Walker",
    phoneNumber: "+1234567807",
    typeOfSubscription: "Basic",
    subscriptionActive: true,
    paymentConfirmed: true,
    dateOfRegistration: new Date("2024-01-10"),
    numberOfDaysRemaining: 7,
    subscriptionStartingDate: new Date("2024-01-15"),
  },
  {
    regNumber: "10018",
    name: "Jennifer Hall",
    phoneNumber: "+1234567808",
    typeOfSubscription: "Premium",
    subscriptionActive: true,
    paymentConfirmed: true,
    dateOfRegistration: new Date("2024-02-20"),
    numberOfDaysRemaining: 10,
    subscriptionStartingDate: new Date("2024-02-25"),
  },
  {
    regNumber: "10019",
    name: "Richard Allen",
    phoneNumber: "+1234567809",
    typeOfSubscription: "Standard",
    subscriptionActive: false,
    paymentConfirmed: false,
    dateOfRegistration: new Date("2024-03-15"),
    numberOfDaysRemaining: 0,
    subscriptionStartingDate: new Date("2024-03-20"),
  },
  {
    regNumber: "10020",
    name: "Susan Young",
    phoneNumber: "+1234567810",
    typeOfSubscription: "Basic",
    subscriptionActive: true,
    paymentConfirmed: true,
    dateOfRegistration: new Date("2024-04-05"),
    numberOfDaysRemaining: 15,
    subscriptionStartingDate: new Date("2024-04-10"),
  },
  {
    regNumber: "10021",
    name: "Joseph Hernandez",
    phoneNumber: "+1234567811",
    typeOfSubscription: "Premium",
    subscriptionActive: true,
    paymentConfirmed: true,
    dateOfRegistration: new Date("2024-05-01"),
    numberOfDaysRemaining: 25,
    subscriptionStartingDate: new Date("2024-05-05"),
  },
  {
    regNumber: "10022",
    name: "Karen King",
    phoneNumber: "+1234567812",
    typeOfSubscription: "Standard",
    subscriptionActive: false,
    paymentConfirmed: false,
    dateOfRegistration: new Date("2024-06-20"),
    numberOfDaysRemaining: 0,
    subscriptionStartingDate: new Date("2024-06-25"),
  },
  {
    regNumber: "10023",
    name: "Charles Wright",
    phoneNumber: "+1234567813",
    typeOfSubscription: "Basic",
    subscriptionActive: true,
    paymentConfirmed: true,
    dateOfRegistration: new Date("2024-07-15"),
    numberOfDaysRemaining: 10,
    subscriptionStartingDate: new Date("2024-07-20"),
  },
  {
    regNumber: "10024",
    name: "Lisa Scott",
    phoneNumber: "+1234567814",
    typeOfSubscription: "Premium",
    subscriptionActive: true,
    paymentConfirmed: true,
    dateOfRegistration: new Date("2024-08-01"),
    numberOfDaysRemaining: 20,
    subscriptionStartingDate: new Date("2024-08-05"),
  },
  {
    regNumber: "10025",
    name: "Thomas Adams",
    phoneNumber: "+1234567815",
    typeOfSubscription: "Standard",
    subscriptionActive: false,
    paymentConfirmed: false,
    dateOfRegistration: new Date("2024-09-10"),
    numberOfDaysRemaining: 0,
    subscriptionStartingDate: new Date("2024-09-15"),
  },
];

export const user = {
  regNumber: "10007",
  name: "George Miller",
  age: "45",
  email: "george.miller@example.com",
  gender: "Male",
  marital: "Married",
  address: "123 Main St, Springfield",
  phoneNumber: "+1234567897",
  medicalClearance: true,
  currentHealthIssue: "None",
  nextOfKin: "Jane Miller",
  nextOfKinPhoneNumber: "+1987654321",
  currentWeight: 90,
  currentHeight: 180,
  bmi: 27.8,
  dateOfRegistration: new Date("2024-01-10"),
  subscriptionStartingDate: new Date("2024-01-30"),
  typeOfSubscription: "Premium",
  subscriptionActive: true,
  paymentConfirmed: true,
  numberOfDaysRemaining: "0",
  subscriptionCost: "40000",
};
