import { columns } from "@/components/table/columns";
import DataTable from "@/components/table/DataTable";
import React from "react";

function AdminPage() {
  const data = [
    {
      regNumber: "10001",
      firstName: "Alice",
      secondName: "Johnson",
      phoneNumber: "+1234567891",
      typeOfSubscription: "Basic",
      subscriptionActive: true,
      paymentConfirmed: true,
      dateOfRegistration: new Date("2024-02-01"),
      numberOfDaysRemaining: 25,
      subscriptionStartingDate: new Date("2024-03-01"),
    },
    {
      regNumber: "10002",
      firstName: "Bob",
      secondName: "Smith",
      phoneNumber: "+1234567892",
      typeOfSubscription: "Premium",
      subscriptionActive: true,
      paymentConfirmed: false,
      dateOfRegistration: new Date("2024-02-10"),
      numberOfDaysRemaining: 40,
      subscriptionStartingDate: new Date("2024-03-05"),
    },
    {
      regNumber: "10003",
      firstName: "Charlie",
      secondName: "Brown",
      phoneNumber: "+1234567893",
      typeOfSubscription: "Standard",
      subscriptionActive: false,
      paymentConfirmed: true,
      dateOfRegistration: new Date("2024-01-20"),
      numberOfDaysRemaining: 0,
      subscriptionStartingDate: new Date("2024-02-15"),
    },
    {
      regNumber: "10004",
      firstName: "Diana",
      secondName: "Prince",
      phoneNumber: "+1234567894",
      typeOfSubscription: "Premium",
      subscriptionActive: true,
      paymentConfirmed: true,
      dateOfRegistration: new Date("2024-03-01"),
      numberOfDaysRemaining: 60,
      subscriptionStartingDate: new Date("2024-03-15"),
    },
    {
      regNumber: "10005",
      firstName: "Edward",
      secondName: "King",
      phoneNumber: "+1234567895",
      typeOfSubscription: "Basic",
      subscriptionActive: false,
      paymentConfirmed: false,
      dateOfRegistration: new Date("2024-01-15"),
      numberOfDaysRemaining: 0,
      subscriptionStartingDate: new Date("2024-01-20"),
    },
    {
      regNumber: "10006",
      firstName: "Fiona",
      secondName: "Adams",
      phoneNumber: "+1234567896",
      typeOfSubscription: "Standard",
      subscriptionActive: true,
      paymentConfirmed: true,
      dateOfRegistration: new Date("2024-02-18"),
      numberOfDaysRemaining: 45,
      subscriptionStartingDate: new Date("2024-02-28"),
    },
    {
      regNumber: "10007",
      firstName: "George",
      secondName: "Miller",
      phoneNumber: "+1234567897",
      typeOfSubscription: "Premium",
      subscriptionActive: false,
      paymentConfirmed: false,
      dateOfRegistration: new Date("2024-01-10"),
      numberOfDaysRemaining: 0,
      subscriptionStartingDate: new Date("2024-01-30"),
    },
    {
      regNumber: "10008",
      firstName: "Hannah",
      secondName: "Clark",
      phoneNumber: "+1234567898",
      typeOfSubscription: "Basic",
      subscriptionActive: true,
      paymentConfirmed: true,
      dateOfRegistration: new Date("2024-02-22"),
      numberOfDaysRemaining: 20,
      subscriptionStartingDate: new Date("2024-03-10"),
    },
    {
      regNumber: "10009",
      firstName: "Ian",
      secondName: "Scott",
      phoneNumber: "+1234567899",
      typeOfSubscription: "Standard",
      subscriptionActive: true,
      paymentConfirmed: false,
      dateOfRegistration: new Date("2024-01-25"),
      numberOfDaysRemaining: 15,
      subscriptionStartingDate: new Date("2024-02-05"),
    },
    {
      regNumber: "10010",
      firstName: "Jane",
      secondName: "Doe",
      phoneNumber: "+1234567800",
      typeOfSubscription: "Premium",
      subscriptionActive: true,
      paymentConfirmed: true,
      dateOfRegistration: new Date("2024-03-05"),
      numberOfDaysRemaining: 90,
      subscriptionStartingDate: new Date("2024-03-20"),
    },
  ];
  return <DataTable data={data} columns={columns}></DataTable>;
}

export default AdminPage;
